### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ItzLuis** [ElementalMinecraftGaming/StableMythicWarriors#4]
Hey I have some questions If you could answer them.

-is this plugin still discontinued (pretty good plugin just wondering why you would discontinue it)
-does the command /mythictitans work
-what kind of abilities are there? So far all I know is SMASH. Also what’s the point of Hunger I don’t understand?
-when I make a race and do /titanegg and get a zombie egg does it apply to all zombies or just that specific one

contact me on discord : ItzLuis#1745 or Instagram: ItzLui_s

**Comment by ElementalMinecraftGaming** [comment]
1. This plugin is indeed discontinued but i making a new version that is much better, it was mainly discontinued because i didn't have the time to keep making this.
2. It should if the current api is still supported but it will only work with registered titans that are nearby
3. I am pretty sure i never finished the abilities
4. Every zombie spawned with the titan egg will become a titan with the abilities of it's race when the command /mythictitans is run.

**Comment by ItzLuis** [comment]
Oh okay what’s the new version going to be called or what is it if I can ask 😅

**Comment by ElementalMinecraftGaming** [comment]
> Oh okay what’s the new version going to be called or what is it if I can ask 😅

Sorry but i can not reveal this information because i don't know if it will be finished any time soon.
